### ISSUE TITLE
Create a mock Dataframe for Xmas Lights prices and Ornaments across mutilple stores (HEB, Kroger, Michaels, Costco)  ( JUPYTER NOTEBOOK )

### ISSUE THREAD

**Issue by carloscodingroadtrip** [carloscodingroadtrip/rice-team-jupyter#13]
Make sure to provide a good name for your Jupyter Notebook.

*** Will starting working on this 2020-12-12 KM***

***KM trying to figure out these comments***

**Comment by Krla20** [comment]
Starting to work on it, will move to in progress 2020-12-12
